server:
  port: 8055
spring:
    mail:
        host: smtp.gmail.com
        username: XXXX@gmail.com
        password: XXXXXXXX
        port: 587
        properties:
            mail:
                  smtp:
                    ssl:
                      trust: smtp.gmail.com
                    auth: true
                    starttls:
                        enable: true
                        required: true



    datasource:
      driverClassName: org.h2.Driver
      name: debitor
      password: ''
      url: jdbc:h2:mem:debitor
      username: sa
      h2:
        console:
          enabled: true
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          hibernate:
            format_sql: true
        show-sql: true
    url: https://interview.brixo.se/api/application
