server:
  port: 8055
spring:
  profiles:
    active: "dev"


---

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver   
    password: dev@123
    url: jdbc:sqlserver://ec2-18-221-230-221.us-east-2.compute.amazonaws.com:1433;databaseName=test
    username: gotracrat
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  url: src//main//resources//debtor.json
  profiles: dev
  mail:
    host: smtp.gmail.com
    username: testbrixo@gmail.com
    password: vqjjaqbbfylyeusf
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true
  scheduling:
    job:
      cron: 0 */5 * * * *

---

spring:
  datasource:
    driverClassName: org.h2.Driver
    name: debitor
    password: ''
    url: jdbc:h2:mem:debitor
    username: sa
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true
      show-sql: true
  url: src//main//resources//debtor.json
  profiles: test
  mail:
    host: smtp.gmail.com
    username: testbrixo@gmail.com
    password: vqjjaqbbfylyeusf
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true
  scheduling:
    job:
      cron: 0 */5 * * * *

---

spring:
  datasource:
    driverClassName: org.h2.Driver
    name: debitor
    password: ''
    url: jdbc:h2:mem:debitor
    username: sa
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true
      show-sql: true
  url: src//main//resources//debtor.json
  profiles: prod
  mail:
    host: smtp.gmail.com
    username: testbrixo@gmail.com
    password: vqjjaqbbfylyeusf
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true
  scheduling:
    job:
      cron: 0 */5 * * * *
